### ISSUE TITLE
2 Errors about installation test

### ISSUE THREAD

**Issue by Shokusei** [anne-gcd/MTG-Link#20]
Hello, @anne-gcd 
I finished installing this app into cent OS ( the server of DDBJ in Japan).
Then, as you said, I carried out the commands below, but errors occurred.
Please check and tell me where is wrong.

(mtglink) [iceplant4561@at138 test]$ mtglink.py DBG -gfa test.gfa -bam test.bam -fastq reads.sorted.fastq -index barcoded.shelve -out results_MTGLink_DBG
Traceback (most recent call last):
  File "/home/iceplant4561/anaconda3/envs/mtglink/bin/mtglink.py", line 38, in <module>
    from main import gfaFile, gfa_name, line_gfa, outDir, subsamplingDir, assemblyDir, evalDir, module
  File "/lustre7/home/iceplant4561/anaconda3/envs/mtglink/bin/main.py", line 48, in <module>
    subparsers = parser.add_subparsers(dest="MTGLink_module", help="MTGLink_module used for the Local Assembly step", required=True)
  File "/home/iceplant4561/anaconda3/envs/mtglink/lib/python3.6/argparse.py", line 1707, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

(mtglink) [iceplant4561@at138 test]$ mtglink.py IRO -gfa test.gfa -bam test.bam -fastq reads.sorted.fastq -index barcoded.shelve -out results_MTGLink_IR
Traceback (most recent call last):
  File "/home/iceplant4561/anaconda3/envs/mtglink/bin/mtglink.py", line 38, in <module>
    from main import gfaFile, gfa_name, line_gfa, outDir, subsamplingDir, assemblyDir, evalDir, module
  File "/lustre7/home/iceplant4561/anaconda3/envs/mtglink/bin/main.py", line 48, in <module>
    subparsers = parser.add_subparsers(dest="MTGLink_module", help="MTGLink_module used for the Local Assembly step", required=True)
  File "/home/iceplant4561/anaconda3/envs/mtglink/lib/python3.6/argparse.py", line 1707, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

and also, I couldn't open the help.

(mtglink) [iceplant4561@at138 test]$ mtglink.py -h
Traceback (most recent call last):
  File "/home/iceplant4561/anaconda3/envs/mtglink/bin/mtglink.py", line 38, in <module>
    from main import gfaFile, gfa_name, line_gfa, outDir, subsamplingDir, assemblyDir, evalDir, module
  File "/lustre7/home/iceplant4561/anaconda3/envs/mtglink/bin/main.py", line 48, in <module>
    subparsers = parser.add_subparsers(dest="MTGLink_module", help="MTGLink_module used for the Local Assembly step", required=True)
  File "/home/iceplant4561/anaconda3/envs/mtglink/lib/python3.6/argparse.py", line 1707, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

I'm expecting your help.

**Comment by anne-gcd** [comment]
Hello @Shokusei,
I'm sorry to hear that you have difficulties running MTG-Link.

I tried to reproduce your errors but I don't have any error when I try to run MTG-Link. 
May I know how you've installed it ?

I would like to mention also that this tool is still in development so there may be some bugs. I'm developing a new version of this tool (which is in the "scale-up" branch) and I will soon update it. So maybe it's best to wait for the new version. It should be out in a few days (end of this week or beginning of next week). 

However, as I don't have the same error message as you, it would be nice if you could tell me how you've installed MTG-Link (via git clone or conda, how you've installed the dependencies,...), so that I can help you.

**Comment by Shokusei** [comment]
I'm sorry, @anne-gcd, I could resolve this problem by updating python to ver.3.9.9.
However, I'd like you to answer a new question of mine.
According to your manual file, mtg-link requires a read file obtained from 10×Genomics, but I have only 150 bp short reads obtained from Illumina Novaseq. 
Can I use this software without 10×Genomics reads?

**Comment by anne-gcd** [comment]
Hello @Shokusei,

MTG-Link takes advantage of the linked-read barcode information to get a subsample of reads of interest for the local assembly of each gap. This is one of the main features of MTG-Link. So you need to have barcodes in your reads' sequences to be able to use MTG-Link.
Thus, you can use MTG-Link with linked read data only (10X Genomics, Haplotagging, stLFR, TELL-Seq).
