### ISSUE TITLE
Question: 10X linked reads as inputs for MTG-Link

### ISSUE THREAD

**Issue by ClarenceHsiang** [anne-gcd/MTG-Link#21]
Dear MTG-Link developers:

Good evening.

I would like to used 10x linked reads for the purpose of gap closing by using MTG-Link,
but in the raw data of 10x linked reads, there are several inputs as shown below:

A-1_S1_L002_R2_001.fastq.gz
A-1_S1_L002_R1_001.fastq.gz
A-1_S1_L001_R2_001.fastq.gz
A-1_S1_L001_R1_001.fastq.gz
A-1_S1_L002_I1_001.fastq.gz
A-1_S1_L001_I1_001.fastq.gz

How could I use these raw data of 10x-linked reads as the input for MTG-Link?
Should I run longranger basic ?

**Comment by anne-gcd** [comment]
Hello @ClarenceHsiang ,

Yes, you have to run `longranger basic` first (here is how to run it: https://support.10xgenomics.com/genome-exome/software/pipelines/latest/advanced/other-pipelines). 
You can then use the output gzipped FASTQ file (located in the subfolder named "outs") as the input linked reads file (arg `-fastq`) for MTG-Link.

Please let me know if you need help to run MTG-Link.

Best, 
Anne
