### ISSUE TITLE
Converting MTG-Link output to VCF

### ISSUE THREAD

**Issue by pontushojer** [anne-gcd/MTG-Link#25]
Hi, 

I am using MTG-Link to call insertions following the instructions under [docs/insertionsvariants_reconstruction](https://github.com/anne-gcd/MTG-Link/blob/master/docs/insertionsvariants_reconstruction/README.md). The output is both an updated GFA and a FASTA containing the assembled sequences. Do you have any recommendations for generating a VCF based on these? I would need an VCF for comparing structural variant calls.

My first idea was to use [minimap2/paftools.js](https://github.com/lh3/minimap2/tree/master/misc) for this. Have you used the same and what parameters did you use in that case?

**Comment by clemaitre** [comment]
Hi Pontus,

Converting the output to VCF format for insertion variant reconstruction is indeed a very useful feature that we had in mind to implement but unfortunately we did not have the time to do so. 

For the experiment we performed in the publication (with the Genome In A Bottle dataset), we did not use the VCF format, as we only compared the insertion sequences (and not the positions) by aligning with Blast each assembled sequence to its corresponding one (extracted from the truth callset VCF).

What we had in mind for the conversion to VCF, was to develop a small Python script that would use both the input VCF (containing insertion site positions) and the FASTA file containing the assembled sequences. The header entries in the FASTA file contain the coordinates on the reference genome of the assembled sequences (+/- 50 bp at each side of the insertion site position reported in the input VCF if you used `vcf2gfa.py` with default parameters). This allows us to link each assembled sequence to its corresponding variant in the VCF file. So in theory, we only need to remove these 50 bp at each side of the assembled sequence and put the resulting sequence in the ALT field of the corresponding line in the VCF file. 
But, as there may be polymorphism in this region between the sample and the reference, these actual extension sizes may vary slightly from the expected 50 bp on either side and a more rigorous way would be to align these extension sequences to the region around the insertion point to identify the coordinates of the sequence to be cut and a more precise insertion site position. This is in line with your idea of using minimap2/paftools, but we can not recommend any parameter sets as we did not test it.

If you test such a conversion, we would be curious to know if this works well. Would you please keep us informed of your results ?

Best,
Claire

**Comment by pontushojer** [comment]
Thanks for your reply Claire! 

I will try and work on some way to make generate VCF based on these two approaches. Let's see how it goes.

**Comment by pontushojer** [comment]
I have generated a script for converting to VCF based on the naive approach so far. Its available under this Gist https://gist.github.com/pontushojer/da2c40de4f8d89c23fa992d6ff6f3cc3 for anyone who is interested.

**Comment by clemaitre** [comment]
Hi Pontus,

Great ! Thank you very much for sharing your script ! It will certainly be useful for other users.
Is it ok with you if I add a link to this Gist in the Readme doc about insertion variant reconstruction ?

Best,
Claire

**Comment by pontushojer** [comment]
Its fine with me 👍
