### ISSUE TITLE
no results if extra `.` in input GFA name 

### ISSUE THREAD

**Issue by pontushojer** [anne-gcd/MTG-Link#26]
Here is a quirky bug that I run into.

I was running MTG-Link with a input GFA file named something like this `final.mtglink_large_insertions.gfa` (Notice there is two dots (`.`) in this name). The GFA was for about  ~400 insertion, multiple of which are confirmed to exist in the queried genome.   

Confusingly none of them would produce any viable contig!? All just ended up listed in `bad_solutions.fasta` with each entry ending in `*_qual.DD`.

After a lot of confusion and rerunning multiple times with not change I started digging into the code. After some more digging i finally found this in the `stats_aligment.py` file. The two lines below are affected

https://github.com/anne-gcd/MTG-Link/blob/3958fc2d1bd0c6f7f871e9100f3eb931fa396f0d/stats_alignment.py#L458C13-L458C59

https://github.com/anne-gcd/MTG-Link/blob/3958fc2d1bd0c6f7f871e9100f3eb931fa396f0d/stats_alignment.py#L478C13-L478C13

To get the  `qry_id` the following expression is used `qry_file.split('/')[-1].split('.')[2]`. Notice that from the final split on `.`  the 3rd  entry (index 2) in the list is taken. In my case with the file `qry_file` has the prefix `final.mtglink_large_insertions.gfa` which will yield `"gfa"` for all insertions. 

For now I just renamed my input GFA but there should probably be a check for additional `.`-symbols in the name or even better use a regex expression here to extract the required string. This would also be beneficial in other places values are extracted from strings.

**Comment by clemaitre** [comment]
Hi Pontus,

Thank you for reporting this issue and for the useful investigation of the problem source.
This is now corrected.

Best,
Claire
